apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-test-app
  labels:
    app: dep-test-app
spec:
  replicas: 1  
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate  
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: dep-test-app-container
        image: shestera/scaletestapp
        ports:
        - name: http
          containerPort: 8080
        resources:
         requests:
           memory: "20Mi"
         limits:
           memory: "20Mi" 