apiVersion: v1
kind: Service
metadata:
  name: svc-test-app
spec:
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 808
      targetPort: 8080
      #nodePort: 30808
  type: NodePort